### ISSUE TITLE
Paper checklist

### ISSUE THREAD

**Issue by Robbybp** [Robbybp/variable-elimination#61]
To-dos before sending to Russell and Larry for review:
- [x] [R-W1] Add discussion of convergence results
  - Average reliability of each method
  - Is there a trend?
  - Nothing underperforms no-elimination on average
  - Improvement in convergence is not uniform
  - Why do we think convergence improves?
  - Note that we could also improve convergence with better initialization/scaling, but this is hard
- [x] [R-W2] Write introduction
- [x] [S-W2] Write conclusion
- [x] [S-W2] Write abstract
- [x] [S-W1] Put incidence matrix plots in paper
- [x] [S-W1] Plot "virtual best" for each model
- [x] [R/S-W3] Review paper and clarify anything that is still confusing
- [x] [S-W1] Add discussion of bar graphs
